<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Добавить запрос на производство продукции");
?>

<?/* $APPLICATION->IncludeComponent(
	"bitrix:iblock.element.add", 
	"littleweb", 
	[
		"AJAX_MODE" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"ALLOW_DELETE" => "N",
		"ALLOW_EDIT" => "N",
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_TO" => "",
		"CUSTOM_TITLE_DETAIL_PICTURE" => "",
		"CUSTOM_TITLE_DETAIL_TEXT" => "",
		"CUSTOM_TITLE_IBLOCK_SECTION" => "",
		"CUSTOM_TITLE_NAME" => "",
		"CUSTOM_TITLE_PREVIEW_PICTURE" => "",
		"CUSTOM_TITLE_PREVIEW_TEXT" => "",
		"CUSTOM_TITLE_TAGS" => "",
		"DEFAULT_INPUT_SIZE" => "30",
		"DETAIL_TEXT_USE_HTML_EDITOR" => "Y",
		"ELEMENT_ASSOC" => "CREATED_BY",
		"GROUPS" => [
			0 => "2",
		],
		"IBLOCK_ID" => "7",
		"IBLOCK_TYPE" => "products",
		"LEVEL_LAST" => "Y",
		"MAX_FILE_SIZE" => "0",
		"MAX_LEVELS" => "100000",
		"MAX_USER_ENTRIES" => "100000",
		"NAV_ON_PAGE" => "10",
		"PREVIEW_TEXT_USE_HTML_EDITOR" => "Y",
		"PROPERTY_CODES" => [
			0 => "13",
			1 => "14",
			2 => "15",
			3 => "16",
			4 => "17",
			5 => "18",
			6 => "19",
			7 => "20",
			8 => "21",
			9 => "22",
			10 => "23",
			11 => "NAME",
			12 => "TAGS",
			13 => "PREVIEW_PICTURE",
			14 => "DETAIL_TEXT",
		],
		"PROPERTY_CODES_REQUIRED" => [
			0 => "15",
			1 => "16",
			2 => "17",
			3 => "20",
			4 => "22",
			5 => "23",
			6 => "NAME",
		],
		"RESIZE_IMAGES" => "Y",
		"SEF_MODE" => "N",
		"STATUS" => "ANY",
		"STATUS_NEW" => "NEW",
		"USER_MESSAGE_ADD" => "Сообщение об успешном добавлении",
		"USER_MESSAGE_EDIT" => "Сообщение об успешном сохранении",
		"USE_CAPTCHA" => "Y",
		"COMPONENT_TEMPLATE" => "littleweb"
	],
	false
); */ ?>
<? $APPLICATION->IncludeComponent(
	"bitrix:iblock.element.add.form", 
	"littleweb", 
	[
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_TO" => "",
		"CUSTOM_TITLE_DETAIL_PICTURE" => "",
		"CUSTOM_TITLE_DETAIL_TEXT" => "Описание",
		"CUSTOM_TITLE_IBLOCK_SECTION" => "",
		"CUSTOM_TITLE_NAME" => "Наименование продукции",
		"CUSTOM_TITLE_PREVIEW_PICTURE" => "Логотип компании",
		"CUSTOM_TITLE_PREVIEW_TEXT" => "",
		"CUSTOM_TITLE_TAGS" => "",
		"DEFAULT_INPUT_SIZE" => "30",
		"DETAIL_TEXT_USE_HTML_EDITOR" => "N",
		"ELEMENT_ASSOC" => "CREATED_BY",
		"GROUPS" => [
			0 => "2",
		],
		"IBLOCK_ID" => "7",
		"IBLOCK_TYPE" => "products",
		"LEVEL_LAST" => "Y",
		"LIST_URL" => "",
		"MAX_FILE_SIZE" => "0",
		"MAX_LEVELS" => "100000",
		"MAX_USER_ENTRIES" => "100000",
		"PREVIEW_TEXT_USE_HTML_EDITOR" => "N",
		"PROPERTY_CODES" => [
			0 => "13",
			1 => "14",
			2 => "15",
			3 => "16",
			4 => "17",
			5 => "18",
			6 => "19",
			7 => "20",
			8 => "21",
			9 => "22",
			10 => "23",
			11 => "NAME",
			12 => "PREVIEW_PICTURE",
			13 => "DETAIL_TEXT",
		],
		"PROPERTY_CODES_REQUIRED" => [
			0 => "13",
		],
		"RESIZE_IMAGES" => "Y",
		"SEF_FOLDER" => "/requests/",
		"SEF_MODE" => "N",
		"STATUS" => "INACTIVE",
		"STATUS_NEW" => "NEW",
		"USER_MESSAGE_ADD" => "Спасибо! Ваша заявка отправлена на модерацию!",
		"USER_MESSAGE_EDIT" => "Спасибо! Ваша заявка отправлена на модерацию!",
		"USE_CAPTCHA" => "Y",
		"COMPONENT_TEMPLATE" => "littleweb",
		"PARAMETERS" => ""
	],
	false
); ?>
<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php") ?>